server:
  port: 8002

spring:
  application:
    name: login-provider-service
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/myapp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 1351503414@qq.com
    password: hqtxzeumbhvtidie    #发送短信后它给你的授权码
    default-encoding: utf-8
    #在阿里云服务器上端口25需申请才能打开，将处理发送邮箱端口改为”465“
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port:port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

mybatis:
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.lin.entity    # 所有Entity别名类所在包


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
    #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: login8002
    #访问路径可以显示IP地址
    prefer-ip-address: true
